### ISSUE TITLE
ThreePIE unable to reconstruct 2-slice simulation

### ISSUE THREAD

**Issue by yiranlus** [ptycho/ptypy#521]
Hi everyone,

I try to reconstruct a 2-slice (slice distance 100 nm, electron ptychography under 80 kV) simulation with ThreePIE. The phases of the two objects are below:

![image](https://github.com/ptycho/ptypy/assets/19369063/172853c7-25aa-4683-be1a-063c9d08b8da)

I use a probe without any aberrations.

However, the reconstructed phase of the first slice is always very weak compared to the second slice. The phases of the two slices are like this:
![image](https://github.com/ptycho/ptypy/assets/19369063/0d4e54d4-43bf-4e39-b088-537a0259a5b9)
![image](https://github.com/ptycho/ptypy/assets/19369063/e09dfdd3-6aab-4881-96c3-cf34366439a6)

Here are the parameter I used for the reconstruction:
```
engines:
  engine00:
    name: "ePIE_multislice"
    numiter: 100
    numiter_contiguous: 10
    alpha: 0.7
    beta: 0.5
    probe_update_start: 20
    record_local_error: false
    object_norm_is_global: true
    number_of_slices: 2
    slice_thickness: 100.0e-9
```

Anyone have idea why I can't get correct phase in this case?
